server {
    listen 80;
    server_name _;

    # Dify API
    location /console/api {
        proxy_pass http://dify-api:5001;
        include /etc/nginx/proxy.conf;
    }

    location /api {
        proxy_pass http://dify-api:5001;
        include /etc/nginx/proxy.conf;
    }

    location /v1 {
        proxy_pass http://dify-api:5001;
        include /etc/nginx/proxy.conf;
    }

    location /files {
        proxy_pass http://dify-api:5001;
        include /etc/nginx/proxy.conf;
    }

    # Dify Web
    location / {
        proxy_pass http://dify-web:3000;
        include /etc/nginx/proxy.conf;
    }
}
